const TEACHER_ROLE = 'profesor';
const STUDENT_ROLE = 'alumno';

const COURSE_TYPE_SINGLE = 'individual';
const COURSE_TYPE_GROUP = 'grupal';

const COURSE_FREQUENCY_ONCE = 'única';
const COURSE_FREQUENCY_WEEKLY = 'semanal';
const COURSE_FREQUENCY_MONTHLY = 'mensual';

const COURSE_NOTIFICATION = 'inscripcion';
const COMMENT_NOTIFICATION = 'comentario';
const COURSE_ACCEPTED_NOTIFICATION = 'inscripcion_aceptada';
const COURSE_REJECTED_NOTIFICATION = 'inscripcion_rechazada';
const BLOCK_COMMENT = 'bloqueado';
const ACCEPT_COMMENT = 'aceptado';

const EDUCATION_LEVEL_PRIMARY = 'primario';
const EDUCATION_LEVEL_SECONDARY = 'secundario';
const EDUCATION_LEVEL_TERTIARY = 'terciario';
const EDUCATION_LEVEL_UNIVERSITY = 'universitario';

const EDUCATION_STATUS_ONGOING = 'en curso';
const EDUCATION_STATUS_PAUSED = 'pausado';
const EDUCATION_STATUS_DROPPED = 'abandonado';
const EDUCATION_STATUS_FINISHED = 'finalizado';

const COURSE_STATUS_PENDING = 'solicitada';
const COURSE_STATUS_ACCEPTED = 'aceptada';
const COURSE_STATUS_FINISHED = 'finalizada';
const COURSE_STATUS_CANCELLED = 'cancelada';

export {
  TEACHER_ROLE,
  STUDENT_ROLE,
  COURSE_TYPE_SINGLE,
  COURSE_TYPE_GROUP,
  COURSE_FREQUENCY_ONCE,
  COURSE_FREQUENCY_WEEKLY,
  COURSE_FREQUENCY_MONTHLY,
  COURSE_ACCEPTED_NOTIFICATION,
  COURSE_REJECTED_NOTIFICATION,
  COURSE_NOTIFICATION,
  COMMENT_NOTIFICATION,
  BLOCK_COMMENT,
  ACCEPT_COMMENT,
  EDUCATION_LEVEL_PRIMARY,
  EDUCATION_LEVEL_SECONDARY,
  EDUCATION_LEVEL_TERTIARY,
  EDUCATION_LEVEL_UNIVERSITY,
  EDUCATION_STATUS_ONGOING,
  EDUCATION_STATUS_PAUSED,
  EDUCATION_STATUS_DROPPED,
  EDUCATION_STATUS_FINISHED,
  COURSE_STATUS_PENDING,
  COURSE_STATUS_ACCEPTED,
  COURSE_STATUS_FINISHED,
  COURSE_STATUS_CANCELLED,
};
