const TEACHER_ROLE = "profesor";
const STUDENT_ROLE = "alumno";

const COURSE_TYPE_SINGLE = "individual";
const COURSE_TYPE_GROUP = "grupal";

const COURSE_FREQUENCY_ONCE = "única";
const COURSE_FREQUENCY_WEEKLY = "semanal";
const COURSE_FREQUENCY_MONTHLY = "mensual";

const COURSE_REQUEST = "inscripcion";
const COMMENT_REQUEST = "comentario";

export {
  TEACHER_ROLE,
  STUDENT_ROLE,
  COURSE_TYPE_SINGLE,
  COURSE_TYPE_GROUP,
  COURSE_FREQUENCY_ONCE,
  COURSE_FREQUENCY_WEEKLY,
  COURSE_FREQUENCY_MONTHLY,
  COURSE_REQUEST,
  COMMENT_REQUEST,
};
